### ISSUE TITLE
Support top level awaits

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/typescript-notebook#13]
* Variables must be available in subsequent cells
* Support class/function hoisting
*

**Comment by DonJayamanne** [comment]
Done, will be shipped soon

**Comment by AgainPsychoX** [comment]
Shouldn't it be reopened as warnings still are visible?

![image](https://user-images.githubusercontent.com/23557839/148701846-b676e480-7204-4085-9acd-175c993088de.png)

_It works okay, but warnings are very annoying..._
