### ISSUE TITLE
Code completion ?

### ISSUE THREAD

**Issue by oguimbal** [DonJayamanne/typescript-notebook#2]
Hi ! Very nice to you to bring this in vscode :)

However, autocompletion stops working when you import local node_modules, or local files:

- `path.cwd()` is correct
- Path completion seems to think I am in %localappdata% (see screenshot)
- Imports are not typed (therefore losing a bit of Typescript developper friendliness)
- ... but it runs.

<p align=center>
<img width=50% src="https://user-images.githubusercontent.com/8973947/109275804-8838c400-7815-11eb-88e6-a8bd7dce76d0.png">
</p>

I'm not sure wether if this is an issue with your extension, or with tslabs, nor if it can be fixed

Thanks !

**Comment by DonJayamanne** [comment]
Closing for now, as this is being handled by VS Code (if it hasn't been addressed please file an issue in VS Code - they are looking into issues related to code completions when using this TypeScript notebook for ipynb formats)
