### ISSUE TITLE
Add support for arquero

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/typescript-notebook#22]
https://github.com/uwdata/arquero

**Comment by DonJayamanne** [comment]
Should be able to get this in by tomorrow, was too easy.
![Screenshot from 2021-09-05 22-28-59](https://user-images.githubusercontent.com/1948812/132165318-6896eb15-d0af-473c-ab3b-09e3bd69f39f.png)
![Screenshot from 2021-09-05 22-29-22](https://user-images.githubusercontent.com/1948812/132165320-d770f3e6-ac5a-47fb-b9aa-846308190633.png)

**Comment by DonJayamanne** [comment]
Automatically detect arquero tables & display HTML view
![Screenshot from 2021-09-05 23-03-32](https://user-images.githubusercontent.com/1948812/132168324-c7744157-ce6d-44d6-9240-91fc40adfec8.png)

**Comment by DonJayamanne** [comment]
@RandomFractals /cc

**Comment by RandomFractals** [comment]
This is very cool. I see you even managed to get arrow data loader working in that example with arrow data display.

Impressive and thank you for adding that data transformation library support. I think it's way better than others I've seen that attempt to do the similar things in JS.

**Comment by RandomFractals** [comment]
The one note I have about this setup, I think it would be better if JS libraries that are automatically imported still have qualifiers. 

Then we don't have to implicitly import `arquero`, but in order to use it, we'd have to specify we want to use `aq.` in our JS/TS code cells.

I believe that would help you parse those code cells and dynamically import the required libraries for those common data and charts libraries to function. In essence, it would be very similar to what ObservableHQ does to speed up JS Notebooks development:

https://observablehq.com/@observablehq/stdlib?collection=@observablehq/introduction#additionalLibrariesSection

**Comment by DonJayamanne** [comment]
> think it would be better if JS libraries that are automatically imported still have qualifiers.

Not sure what your mean by this.
Are you suggesting I create a global variable `aq` and make it available  for all notebooks and have it point to arquero?
If that's the suggestion, then I'm not a fan of that. This is a node.js notebook, idea can write any node.js code.

Users can always write `const aq = require('arquero')` or `import * as aq from 'arquero'`

**Comment by DonJayamanne** [comment]
I think we can make that possible via some other mechanism, such as templates or some settings to always automatically import some motors.
A template seems much better, this way the cell with the imports can be at the top and collapsed.

**Comment by DonJayamanne** [comment]
Basically I'll let users use renderers like yours & they'll work very well. Else I end up re-inventing the wheel and users are locked to a specific extension as I (notebook provider) control the mime type.

@RandomFractals I'm closing this issue for now, as this was originally created to support arquero.
Please feel free to create a separate issue if you have other suggestions, you might be interested in the issue for observable notebooks/inspector.

**Comment by RandomFractals** [comment]
agreed. I am not a huge fan of globals either, and I see how that would restrict node.js notebooks to be used only with your kernel.

The less customizations you add the better. I am all for reusing and creating more rich renderers.

Exploring templates based on some common use cases is a good idea and we should probably create some as part of renderers with examples I started building or in this extension later.

Thanks for adding `arquero` support. This opens many doors for massaging data in JS notebooks.
