### ISSUE TITLE
Remove Tensorflow from activity bar

### ISSUE THREAD

**Issue by texastoland** [DonJayamanne/typescript-notebook#24]
I'm excited to try your TS notebook support! But the most recent update added an icon to my already cluttered sidebar.

I understand it's only a couple clicks to hide it. But the sidebar is usually reserved for cross-functional features like explorers or source control. It was also tricky to track down which extension contributed Tensorflow. I found it in settings but there's no visual cue and I have no ML extensions installed.

I propose moving Tensorflow to a panel with a more contextual name 🙏🏼

**Comment by DonJayamanne** [comment]
>  But the sidebar is usually reserved for cross-functional features like explorers or

Not sure I agree about this.

However I do agree with the over all issue, & i think the solution is to hide this and dipslay it only when necessary.
Optionally I'll add a setting to hide this permantently.

**Comment by DonJayamanne** [comment]
Fixed, will be in the next release.
* It will not be visible unless you use @tensorflow/tfjs-vis (the package that provides visualization) 
* Optionally you can set the setting `node_notebook.disableTensorflowVis = false` to hide this permanely (even if you do use the tensorflow visualizations)

https://github.com/DonJayamanne/typescript-notebook/commit/888b1d28f74ab041214a60aafafabad00df81acd

**Comment by texastoland** [comment]
That's super thank you 🙌🏼
