### ISSUE TITLE
Star activation causes a slew of activations

### ISSUE THREAD

**Issue by kieferrm** [DonJayamanne/typescript-notebook#4]
Because of https://github.com/DonJayamanne/typescript-notebook/blob/0daecb6fd962ed7d7cff5ab495483900a016f482/package.json#L45-L46

when you open a new empty VS Code window - no open folder and no open files - the Jupyter extension activates which in turn activates the Python extension.

**Comment by DonJayamanne** [comment]
Aah, didn't think about that. The intention was to ensure the kernel gets registered without any user intervention. Will have to re-think that.

**Comment by DonJayamanne** [comment]
Oh shot, i can change it to activate when the notebook opens.
Will fix.

**Comment by DonJayamanne** [comment]
Fixed
