### ISSUE TITLE
Javascript/Typescript not compiling / Stuck at pending

### ISSUE THREAD

**Issue by xposedbones** [DonJayamanne/typescript-notebook#42]
I was excited to start using this but I can't get anything javascript/typescript to compile.

No errors pops up, it's just stuck at `Pending`.  I have tried installing the Node REPL extension in vscode but that didn't help.

I have typescript installed globally
* Typescript version: 4.4.4
* Node version: 12.20.0
* npm version: 6.14.8

![image](https://user-images.githubusercontent.com/1087405/140101994-061615a9-3b52-4be3-8c40-4379d0bcf0d7.png)

If I switch the compiler to HTML everything is rendered.

**Comment by DonJayamanne** [comment]
I've managed to repro this, will be releasing a new version ASAP.

**Comment by DonJayamanne** [comment]
I"ve uploaded a new version, please let me know if that fixes it.
If not, please do feel free to re-open this issue or create a new one.

**Comment by brooksvb** [comment]
Hi, I have the same issue after installing for the first time and can't run anything.

I've tried running a few of the built-in sample notebooks but none of the cells will run, and just have the pending icon in the bottom left.

### System
* `node -v`: v16.6.1
* `npm -v`: 8.1.3
* `tsc -v`: 4.5.2

All VS Code extensions are up-to-date.
