### ISSUE TITLE
notebook not working with wsl2 Integration

### ISSUE THREAD

**Issue by Napster2709** [DonJayamanne/typescript-notebook#44]
I was trying to use Node.js Notebook with my normal vscode setup. 

I use vscode with an WSL2 Integration. Node is installed inside wsl and Windows itself. 

Trying to use the notebook with a wsl Integration enabled results in following behaviour:

![image](https://user-images.githubusercontent.com/26511446/140628303-484822ac-0ab4-4c68-82ef-c4116794c2af.png)

It stays pending and never resolves the status. Doing the same under a "native" vscode instance works fine. 

WSL: Ubuntu
Node version: 16.10.0 (WSL) / 16.13.0 (Windows)

**Comment by DonJayamanne** [comment]
Oh, sorry, fixed, will be pushing a new version ASAP

**Comment by DonJayamanne** [comment]
I"ve uploaded a new version, please let me know if that fixes it.
If not, please do feel free to re-open this issue or create a new one.

**Comment by Napster2709** [comment]
Fixed it thank you.

**Comment by dvingo** [comment]
Hello, first, thanks for the extension!

It appears that this is no longer working - same issue where the UI stays in pending status and never returns. I have verified the extension works with direct windows integration (not using a WSL remote).
