### ISSUE TITLE
Gather still showing up 

### ISSUE THREAD

**Issue by claudiaregio** [DonJayamanne/typescript-notebook#5]
Gather icon still showing up in the cell toolbar for TypeScript notebook. 
I can't get the kernel to connect or run, but potentially user issues when user tries to click Gather. 

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/19276747/111920465-644f5380-8a4c-11eb-9fb2-25125c095171.png">

**Comment by DonJayamanne** [comment]
This is a bug in gather extension, it should not show up for non python notebooks.
