### ISSUE TITLE
Viewing real errors

### ISSUE THREAD

**Issue by spookyuser** [DonJayamanne/typescript-notebook#59]
Hi, I really love this extension, but one thing I'm struggling with is seeing the actual errors associated with code instead of where they are. E.g

![image](https://user-images.githubusercontent.com/16196262/162717769-df771941-4d64-4749-ac5b-1eec5914fe56.png)

If there is an obvious option i'm missing, sorry!

**Comment by DonJayamanne** [comment]
Fixed, duplicate of https://github.com/DonJayamanne/typescript-notebook/issues/51
