### ISSUE TITLE
Long time vision

### ISSUE THREAD

**Issue by unuunc** [DonJayamanne/typescript-notebook#62]
Hi, 

this is a question , not issue.

I see the activity in almost all viscose notebooks has reduced ( activity means adding feature etc) , I remember hearing that vscode native api is not stable that is delaying the process. is it still the case?

I am adding this in my long term workflow , so worried if this project will be continued or not ? (Last PR that I see was on Nov , 2021. )

Any indicators will helpful.

Thanks for the lovely extension.

Regards

**Comment by DonJayamanne** [comment]
this extension will continue to be supported. 
right now this extension uses stand api instead of any proposed api. 
im sorry i haven't been able to focus on this for a while, as i recently relocated and am still in the process of settling in .
